default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: ag_backend_dev

test:
  <<: *default
  database: ag_backend_test

